on:
  push:
    branches:
      - main
jobs:
  cd-storage:
    env:
      AWS_REGION: eu-west-3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Storage stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: db21038
          template: cf-stacks/STD21089.yml
